apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-monkey-deployment
spec:
  selector:
    matchLabels:
      app: pod-monkey
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-monkey
    spec:
      volumes:
      - name: pod-monkey-config-volume
        configMap: 
          name: pod-chaos-monkey-config
          items:
            - key: pod_chaos_monkey.yml
              path: pod_chaos_monkey.yml
      containers:
      - name: pod-monkey
        image: yourcontainerregistery/podchaosmonkey
        volumeMounts:
        - name: pod-monkey-config-volume
          mountPath: "/app/config"
          readOnly: true
